name: android_tools
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2026.01.1+26

environment:
  sdk: ^3.10.8

dependencies:
  sentry_flutter: ^9.9.0
  flutter:
    sdk: flutter
  adb_dart: ^1.2.0
  aapt_dart: ^1.0.0
  # adb_dart:
  #  path: ../../adb_dart
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  dart_mappable: ^4.6.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  flutter_svg: ^2.2.3
  logger: ^2.6.2
  equatable: ^2.0.7
  rxdart: ^0.28.0
  path: ^1.9.1
  desktop_drop: ^0.7.0
  file_picker: ^10.3.7
  url_launcher: ^6.3.2
  mime: ^1.0.0
  package_info_plus: ^9.0.0
  bitsdojo_window: ^0.1.6
  auto_updater: ^1.0.0
  intl: ^0.20.2
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0

  drift: ^2.30.1
  drift_flutter: ^0.2.8

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.1
  drift_dev: ^2.30.1

flutter:
  uses-material-design: true

  assets:
    - assets/android_versions/
    - assets/pixels/
    - assets/images/
    - assets/images/file/
    - assets/images/file_extensions/
    - assets/images/folder/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing.otf
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: android-tools
  org: thomas-bernard
